services:

  node1:
    image: cockroachdb/cockroach:v23.1.11
    hostname: node1
    container_name: node1
    command: start --insecure --join=node1,node2,node3
    networks:
      - app-network

  node2:
    image: cockroachdb/cockroach:v23.1.11
    hostname: node2
    container_name: node2
    command: start --insecure --join=node1,node2,node3
    networks:
      - app-network

  node3:
    image: cockroachdb/cockroach:v23.1.11
    hostname: node3
    container_name: node3
    command: start --insecure --join=node1,node2,node3
    networks:
      - app-network

  haproxy:
    hostname: haproxy
    image: timveil/dynamic-haproxy:latest
    ports:
      - 26257:26257
      - 8080:8080
      - 8081:8081
    environment:
      - NODES=node1 node2 node3
    links:
      - node1
      - node2
      - node3
    networks:
    - app-network

networks:
  app-network:
    driver: bridge
